### ISSUE TITLE
Oval shaped thumbnails in owl carousel

### ISSUE THREAD

**Issue by singhayushh** [archcraft-os/archcraft-os.github.io#18]
Under `Join the Community` section in index.html, the thumbnails are getting weirdly oval-shaped due to some default css properties of owl carousel. Screenshot below for reference.

Fix would require a small change. ...Issuing a PR for the same.

<kbd>

![image](https://user-images.githubusercontent.com/52620158/121297841-8dc3a100-c910-11eb-84f7-992ca6bf3702.png)

</kbd>

**Comment by adi1090x** [comment]
Thanks.
